version = 0.1

[default.deploy.parameters]
stack_name = "guardian-stack"
resolve_s3 = true
s3_prefix = "guardian-stack"
region = "us-east-1"
profile = "guardian-deployer"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
